@Library('my-shared-library') _

pipeline {
    agent any
    stages {
        stage('Notify Start') {
            steps {
                script { new com.helper.Notification(this).send("Started") }
            }
        }
        stage('Dev Environment') {
            steps { echo "Deploying to Development..." }
        }
        stage('Test Environment') {
            steps { echo "Deploying to Testing..." }
        }
        stage('Prod Environment') {
            steps { echo "Deploying to Production..." }
        }
    }
    post {
        success { script { new com.helper.Notification(this).send("Success") } }
        failure { script { new com.helper.Notification(this).send("Failure") } }
        unstable { script { new com.helper.Notification(this).send("Unstable") } }
    }
}
